name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Build and deploy
      run: npm run deploy
      env:
        token: ${{ secrets.SERVER_KEY }}
         # deploy token is used to build and deploy to a gh-pages branch 
         # (needs permission to create a branch, build the app and modify that branch, 
         # push changes to that branch, and deploy to github pages)
